#!/usr/bin/env bash

# Required
#
export SERVER_URL="" # e.g. "http://127.0.0.1:3000" in development or "http(s)://my-server-example.com" in production
export CLIENT_URL="" # e.g. "http://127.0.0.1:4200" in development or "http(s)://my-client-example.com" in production
#
export GOOGLE_CLIENTID="" # unique client_id generated by google
export GOOGLE_SECRET="" # unique client_secret generated by google
#
# Google smtp server used for notifications
export YUMMY_SMTP="" # for example "smtps://your-gmail-account-name:your-gmail-account-password@smtp.gmail.com"

# Required in production only
#
export YUMMY_DB="" # database path, e.g. ds031179.mlab.com:31179/prod
export YUMMY_USER="" # database username
export YUMMY_PASSWORD="" # database password
#
# Secret token used for authentication. Can be anything
export SECRET="" # e.g. "secret"

# Required for deployment scripts
#
export SERVER_REPO="" # heroku git repository for server application
export CLIENT_REPO="" # heroku git repository for client application
#
# Airbrake error report service credentials
export AIRBRAKE_PID=""  # projectId
export AIRBRAKE_PKEY="" # projectKey
